from implementation.task import Task, Tasks


def test_task_count():
    task = Task(task=Tasks.COUNT)
    assert sum(task.solution) == 100


def test_task_position():
    task = Task(task=Tasks.POSITION)
    assert sum(task.solution) == 5050
    assert task.solution[0] == 1
    assert task.solution[99] == 100


def test_task_fizzbuzz_complete():
    task = Task(task=Tasks.FIZZBUZZ_COMPLETE)
    assert all(
        task.solution
        == [
            1,
            2,
            -1,
            4,
            -2,
            -1,
            7,
            8,
            -1,
            -2,
            11,
            -1,
            13,
            14,
            -3,
            16,
            17,
            -1,
            19,
            -2,
            -1,
            22,
            23,
            -1,
            -2,
            26,
            -1,
            28,
            29,
            -3,
            31,
            32,
            -1,
            34,
            -2,
            -1,
            37,
            38,
            -1,
            -2,
            41,
            -1,
            43,
            44,
            -3,
            46,
            47,
            -1,
            49,
            -2,
            -1,
            52,
            53,
            -1,
            -2,
            56,
            -1,
            58,
            59,
            -3,
            61,
            62,
            -1,
            64,
            -2,
            -1,
            67,
            68,
            -1,
            -2,
            71,
            -1,
            73,
            74,
            -3,
            76,
            77,
            -1,
            79,
            -2,
            -1,
            82,
            83,
            -1,
            -2,
            86,
            -1,
            88,
            89,
            -3,
            91,
            92,
            -1,
            94,
            -2,
            -1,
            97,
            98,
            -1,
            -2,
        ]
    )
